/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ChemicalElement, ReactionConfig } from './types';

export const ELEMENTS_DATA: ChemicalElement[] = [
  // Period 1
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    mass: 1.008,
    category: 'reactive-nonmetal',
    period: 1,
    group: 1,
    state: 'gas',
    electronConfig: '1s¹',
    shells: [1],
    summary: 'The most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.',
    funFact: 'Highly flammable, it was once used to float the infamous Hindenburg airship. It is the fuel that powers stars through nuclear fusion.',
    discoveredBy: 'Henry Cavendish',
    year: 1766,
    density: '0.08988 g/L',
    meltingPoint: '14.01 K (-259.14 °C)',
    boilingPoint: '20.28 K (-252.87 °C)',
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    mass: 4.0026,
    category: 'noble-gas',
    period: 1,
    group: 18,
    state: 'gas',
    electronConfig: '1s²',
    shells: [2],
    summary: 'A colorless, odorless, tasteless, non-toxic, and inert gas. It is the second lightest and second most abundant element in the observable universe.',
    funFact: 'Helium becomes a superfluid (liquefied with zero viscosity) when cooled below 2.17 K, allowing it to climb up the walls of its container!',
    discoveredBy: 'Jules Janssen, Norman Lockyer',
    year: 1868,
    density: '0.1786 g/L',
    meltingPoint: '0.95 K (-272.2 °C)',
    boilingPoint: '4.22 K (-268.93 °C)',
  },

  // Period 2
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    mass: 6.94,
    category: 'alkali-metal',
    period: 2,
    group: 1,
    state: 'solid',
    electronConfig: '[He] 2s¹',
    shells: [2, 1],
    summary: 'A soft, silvery-white alkali metal. It is the least dense of all solid chemical elements.',
    funFact: 'Lithium is so light that it can float on oil, and it is highly reactive, bursting into Crimson flame when introduced to water.',
    discoveredBy: 'Johan August Arfwedson',
    year: 1817,
    density: '0.534 g/cm³',
    meltingPoint: '453.69 K (180.54 °C)',
    boilingPoint: '1615 K (1342 °C)',
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    mass: 9.0122,
    category: 'alkaline-earth',
    period: 2,
    group: 2,
    state: 'solid',
    electronConfig: '[He] 2s²',
    shells: [2, 2],
    summary: 'A relatively rare element in the universe, often forming into mineral gemstones like emerald and aquamarine.',
    funFact: 'Beryllium is highly transparent to X-rays, making it the choice element for constructing the output window of X-ray tube assemblies.',
    discoveredBy: 'Louis Nicolas Vauquelin',
    year: 1798,
    density: '1.85 g/cm³',
    meltingPoint: '1560 K (1287 °C)',
    boilingPoint: '2742 K (2469 °C)',
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    mass: 10.81,
    category: 'metalloid',
    period: 2,
    group: 13,
    state: 'solid',
    electronConfig: '[He] 2s² 2p¹',
    shells: [2, 3],
    summary: 'A low-abundance metalloid produced by cosmic ray spallation and supernovae rather than stellar nucleosynthesis.',
    funFact: 'Boron compounds burn with a brilliant, supernatural green flame flare and are heavily used in flare fireworks.',
    discoveredBy: 'Joseph Louis Gay-Lussac, Louis Jacques Thénard',
    year: 1808,
    density: '2.08 g/cm³',
    meltingPoint: '2349 K (2076 °C)',
    boilingPoint: '4200 K (3927 °C)',
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    mass: 12.011,
    category: 'reactive-nonmetal',
    period: 2,
    group: 14,
    state: 'solid',
    electronConfig: '[He] 2s² 2p²',
    shells: [2, 4],
    summary: 'The chemical basis of all known organic life. Carbon can bond with many other elements to form nearly ten million compounds.',
    funFact: 'Depending on atomic bonding geometry, Carbon can exist as graphite (ultra-soft, conducts electricity) or diamond (hardest natural mineral, electrical insulator).',
    discoveredBy: 'Ancient civilizations',
    year: -3750,
    density: '2.267 g/cm³',
    meltingPoint: '3823 K (3550 °C)',
    boilingPoint: '4300 K (4027 °C)',
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    mass: 14.007,
    category: 'reactive-nonmetal',
    period: 2,
    group: 15,
    state: 'gas',
    electronConfig: '[He] 2s² 2p³',
    shells: [2, 5],
    summary: 'A common element in the universe, believed to have been synthesized by stellar fusion processes. It makes up 78% of Earth\'s atmosphere.',
    funFact: 'Liquid Nitrogen is extremely cold, boiling at 77 K (-196 °C), and is popular for instant freezing of things and cooling supercomputers.',
    discoveredBy: 'Daniel Rutherford',
    year: 1772,
    density: '1.251 g/L',
    meltingPoint: '63.15 K (-210 °C)',
    boilingPoint: '77.36 K (-195.79 °C)',
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    mass: 15.999,
    category: 'reactive-nonmetal',
    period: 2,
    group: 16,
    state: 'gas',
    electronConfig: '[He] 2s² 2p⁴',
    shells: [2, 6],
    summary: 'A highly reactive nonmetal and oxidizing agent. It is crucial for respiration in aerobic life forms and composition of water.',
    funFact: 'Liquid Oxygen is highly paramagnetic and can be suspended in mid-air between the poles of a powerful electromagnetic horseshoe magnet!',
    discoveredBy: 'Carl Wilhelm Scheele, Joseph Priestley',
    year: 1771,
    density: '1.429 g/L',
    meltingPoint: '54.36 K (-218.79 °C)',
    boilingPoint: '90.2 K (-182.95 °C)',
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    mass: 18.998,
    category: 'halogen',
    period: 2,
    group: 17,
    state: 'gas',
    electronConfig: '[He] 2s² 2p⁵',
    shells: [2, 7],
    summary: 'The most electronegative and chemically reactive of all elements. It represents an extremely toxic, pale yellow corrosive halogen gas.',
    funFact: 'Fluorine is so incredibly reactive that it can ignite metals, water, glass, and even asbestos on contact with bright white fire!',
    discoveredBy: 'Henri Moissan',
    year: 1886,
    density: '1.7 g/L',
    meltingPoint: '53.48 K (-219.67 °C)',
    boilingPoint: '85.03 K (-188.11 °C)',
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    mass: 20.18,
    category: 'noble-gas',
    period: 2,
    group: 18,
    state: 'gas',
    electronConfig: '[He] 2s² 2p⁶',
    shells: [2, 8],
    summary: 'A chemically inert noble gas. Neon glows with a brilliant reddish-orange discharge light when excited in a high voltage vacuum tube.',
    funFact: 'Neon is the second lightest noble gas but maintains 40 times the refrigerating capacity of liquid helium and three times that of liquid hydrogen.',
    discoveredBy: 'Morris Travers, William Ramsay',
    year: 1898,
    density: '0.9002 g/L',
    meltingPoint: '24.56 K (-248.59 °C)',
    boilingPoint: '27.07 K (-246.08 °C)',
  },

  // Period 3
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    mass: 22.99,
    category: 'alkali-metal',
    period: 3,
    group: 1,
    state: 'solid',
    electronConfig: '[Ne] 3s¹',
    shells: [2, 8, 1],
    summary: 'A high-reactivity, soft, silvery alkali metal. It is highly abundant and reacts aggressively with moisture.',
    funFact: 'Pure sodium is soft enough to slice with a butter knife, but explodes in water to generate hydrogen gas and highly caustic sodium hydroxide.',
    discoveredBy: 'Humphry Davy',
    year: 1807,
    density: '0.968 g/cm³',
    meltingPoint: '370.87 K (97.72 °C)',
    boilingPoint: '1156 K (883 °C)',
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    mass: 24.305,
    category: 'alkaline-earth',
    period: 3,
    group: 2,
    state: 'solid',
    electronConfig: '[Ne] 3s²',
    shells: [2, 8, 2],
    summary: 'A shiny gray alkaline earth metal. It is highly reactive but safeguarded by a thin, protective oxide passivating film.',
    funFact: 'When ignited, magnesium metal burns with an blindingly intense white light, generating enough heat to spark underwater and melt steel.',
    discoveredBy: 'Joseph Black',
    year: 1755,
    density: '1.738 g/cm³',
    meltingPoint: '923 K (650 °C)',
    boilingPoint: '1363 K (1090 °C)',
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminium',
    mass: 26.982,
    category: 'post-transition-metal',
    period: 3,
    group: 13,
    state: 'solid',
    electronConfig: '[Ne] 3s² 3p¹',
    shells: [2, 8, 3],
    summary: 'A lightweight silvery-white post-transition metal and the most abundant metallic element in Earth\'s continental crust.',
    funFact: 'In the 1850s, aluminum was rarer and more expensive than gold. Emperor Napoleon III served meals on aluminum plates to his most esteemed guests!',
    discoveredBy: 'Hans Christian Ørsted',
    year: 1825,
    density: '2.70 g/cm³',
    meltingPoint: '933.47 K (660.32 °C)',
    boilingPoint: '2792 K (2519 °C)',
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    mass: 28.085,
    category: 'metalloid',
    period: 3,
    group: 14,
    state: 'solid',
    electronConfig: '[Ne] 3s² 3p²',
    shells: [2, 8, 4],
    summary: 'A hard, dark crystalline metalloid. Silicon is a semiconductor and serves as the molecular backbone of the computer microchip industry.',
    funFact: 'Silicon comprises about 27.7% of Earth\'s crust, primarily in the form of quartz sand, which is melted into liquid to manufacture ultra-clear glass.',
    discoveredBy: 'Jöns Jacob Berzelius',
    year: 1823,
    density: '2.329 g/cm³',
    meltingPoint: '1687 K (1414 °C)',
    boilingPoint: '3538 K (3265 °C)',
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    mass: 30.974,
    category: 'reactive-nonmetal',
    period: 3,
    group: 15,
    state: 'solid',
    electronConfig: '[Ne] 3s² 3p³',
    shells: [2, 8, 5],
    summary: 'A highly reactive, non-metallic element with multiple allotropes, primarily white phosphorus and red phosphorus.',
    funFact: 'White phosphorus has a spooky, haunting glow when exposed to oxygen in the dark—giving rise to the word \'phosphorescence\'.',
    discoveredBy: 'Hennig Brand',
    year: 1669,
    density: '1.823 g/cm³',
    meltingPoint: '317.3 K (44.15 °C)',
    boilingPoint: '553.6 K (280.5 °C)',
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    mass: 32.06,
    category: 'reactive-nonmetal',
    period: 3,
    group: 16,
    state: 'solid',
    electronConfig: '[Ne] 3s² 3p⁴',
    shells: [2, 8, 6],
    summary: 'An abundant, multivalent nonmetal with bright yellow crystalline structure. Found in hot springs and volcanic environments.',
    funFact: 'While pure sulfur itself is completely odorless, its bacterial organic configurations (like hydrogen sulfide) smell like rotten eggs.',
    discoveredBy: 'Ancient civilizations',
    year: -2000,
    density: '2.07 g/cm³',
    meltingPoint: '388.36 K (115.21 °C)',
    boilingPoint: '717.8 K (444.6 °C)',
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    mass: 35.45,
    category: 'halogen',
    period: 3,
    group: 17,
    state: 'gas',
    electronConfig: '[Ne] 3s² 3p⁵',
    shells: [2, 8, 7],
    summary: 'A highly reactive, toxic green-yellow halogen gas. Crucial disinfectant and component in table salt.',
    funFact: 'Chlorine was weaponized as a choking agent in World War I, and is highly reactive with alkali metals to form standard table salt.',
    discoveredBy: 'Carl Wilhelm Scheele',
    year: 1774,
    density: '3.2 g/L',
    meltingPoint: '171.6 K (-101.5 °C)',
    boilingPoint: '239.11 K (-34.04 °C)',
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    mass: 39.948,
    category: 'noble-gas',
    period: 3,
    group: 18,
    state: 'gas',
    electronConfig: '[Ne] 3s² 3p⁶',
    shells: [2, 8, 8],
    summary: 'The third most abundant gas in Earth\'s atmosphere. Chemically inert and used to safeguard delicate historic artifacts.',
    funFact: 'Argon is used to fill double-glazed windows as a thermal barrier because its thermal conductivity is significantly lower than dry air!',
    discoveredBy: 'Lord Rayleigh, William Ramsay',
    year: 1894,
    density: '1.784 g/L',
    meltingPoint: '83.8 K (-189.35 °C)',
    boilingPoint: '87.3 K (-185.85 °C)',
  },

  // Period 4
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    mass: 39.098,
    category: 'alkali-metal',
    period: 4,
    group: 1,
    state: 'solid',
    electronConfig: '[Ar] 4s¹',
    shells: [2, 8, 8, 1],
    summary: 'An extremely reactive alkali metal. Rapidly oxidizes in air and coordinates nerve transmissions in biological cells.',
    funFact: 'Bananas are rich in Potassium, meaning they are naturally slightly radioactive because they contain trace amounts of potassium-40 isotopics!',
    discoveredBy: 'Humphry Davy',
    year: 1807,
    density: '0.89 g/cm³',
    meltingPoint: '336.5 K (63.35 °C)',
    boilingPoint: '1032 K (759 °C)',
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    mass: 40.078,
    category: 'alkaline-earth',
    period: 4,
    group: 2,
    state: 'solid',
    electronConfig: '[Ar] 4s²',
    shells: [2, 8, 8, 2],
    summary: 'A reactive alkaline earth metal that turns yellow when exposed to air. Essential constituent of bones, teeth, and shells.',
    funFact: 'Calcium carbonate makes up limestone, chalk, marble, and also seashells. It is the fifth most abundant element in Earth\'s crust.',
    discoveredBy: 'Humphry Davy',
    year: 1808,
    density: '1.55 g/cm³',
    meltingPoint: '1115 K (842 °C)',
    boilingPoint: '1757 K (1484 °C)',
  },
  {
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    mass: 47.867,
    category: 'transition-metal',
    period: 4,
    group: 4,
    state: 'solid',
    electronConfig: '[Ar] 3d² 4s²',
    shells: [2, 8, 10, 2],
    summary: 'A lustrous transition metal with low density, high strength, and unparalleled fatigue and corrosion resistance.',
    funFact: 'Titanium is named after the Titans of Greek mythology. It is as strong as steel but 45% lighter, making it essential for aerospace engineering.',
    discoveredBy: 'William Gregor',
    year: 1791,
    density: '4.506 g/cm³',
    meltingPoint: '1941 K (1668 °C)',
    boilingPoint: '3560 K (3287 °C)',
  },
  {
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    mass: 51.996,
    category: 'transition-metal',
    period: 4,
    group: 6,
    state: 'solid',
    electronConfig: '[Ar] 3d⁵ 4s¹',
    shells: [2, 8, 13, 1],
    summary: 'A steely-gray, lustrous, hard metal with high corrosion resistance, essential for production of stainless steel.',
    funFact: 'Rubies get their deep blood-red color, and emeralds get their rich green hue, from trace chromium deposits replacing standard aluminum in the crystal.',
    discoveredBy: 'Louis Nicolas Vauquelin',
    year: 1797,
    density: '7.19 g/cm³',
    meltingPoint: '2180 K (1907 °C)',
    boilingPoint: '2944 K (2671 °C)',
  },
  {
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    mass: 54.938,
    category: 'transition-metal',
    period: 4,
    group: 7,
    state: 'solid',
    electronConfig: '[Ar] 3d⁵ 4s²',
    shells: [2, 8, 13, 2],
    summary: 'A hard, brittle, silvery metal often found in minerals combined with iron. Essential for industrial metal alloying.',
    funFact: 'Manganese dioxide was used since the Stone Age in cave painting pigments. It prevents rusting and improves strength in military iron structures.',
    discoveredBy: 'Carl Wilhelm Scheele',
    year: 1774,
    density: '7.21 g/cm³',
    meltingPoint: '1519 K (1246 °C)',
    boilingPoint: '2334 K (2061 °C)',
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    mass: 55.845,
    category: 'transition-metal',
    period: 4,
    group: 8,
    state: 'solid',
    electronConfig: '[Ar] 3d⁶ 4s²',
    shells: [2, 8, 14, 2],
    summary: 'The most common element on Earth by mass, forming much of Earth\'s outer and inner core. Highly vital for metabolism.',
    funFact: 'The red color of soil on Mars is caused by iron oxide (rust) on its surface, and the red of human blood cells is iron routing oxygen.',
    discoveredBy: 'Before 5000 BC',
    year: -5000,
    density: '7.874 g/cm³',
    meltingPoint: '1811 K (1538 °C)',
    boilingPoint: '3134 K (2861 °C)',
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    mass: 58.693,
    category: 'transition-metal',
    period: 4,
    group: 10,
    state: 'solid',
    electronConfig: '[Ar] 3d⁸ 4s²',
    shells: [2, 8, 16, 2],
    summary: 'A silvery-white lustrous transition metal with a subtle golden tinge. Resists corrosion and heat.',
    funFact: 'Earth\'s core contains about 10% pure nickel alongside iron, generating the planet\'s life-shielding geomagnetic field.',
    discoveredBy: 'Axel Fredrik Cronstedt',
    year: 1751,
    density: '8.908 g/cm³',
    meltingPoint: '1728 K (1455 °C)',
    boilingPoint: '3186 K (2913 °C)',
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    mass: 63.546,
    category: 'transition-metal',
    period: 4,
    group: 11,
    state: 'solid',
    electronConfig: '[Ar] 3d¹⁰ 4s¹',
    shells: [2, 8, 18, 1],
    summary: 'A soft, malleable, and ductile metal with exceptionally high thermal and electrical conductivity.',
    funFact: 'Copper has natural antibacterial and antiviral properties. Superbugs, bacteria, and viruses die within hours on contact with pure copper surfaces.',
    discoveredBy: 'Middle East civilizations',
    year: -9000,
    density: '8.96 g/cm³',
    meltingPoint: '1357.77 K (1084.62 °C)',
    boilingPoint: '2835 K (2562 °C)',
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    mass: 65.38,
    category: 'transition-metal',
    period: 4,
    group: 12,
    state: 'solid',
    electronConfig: '[Ar] 3d¹⁰ 4s²',
    shells: [2, 8, 18, 2],
    summary: 'A slightly brittle gray metal at room temperature, famous for rust-proofing and biological enzyme catalysis.',
    funFact: 'Zinc is used to galvanize steel to prevent rust. Roman brass alloy was produced by melting copper together with zinc ores around 200 BC.',
    discoveredBy: 'Indian metallurgists',
    year: 1000,
    density: '7.14 g/cm³',
    meltingPoint: '692.68 K (419.53 °C)',
    boilingPoint: '1180 K (907 °C)',
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    mass: 79.904,
    category: 'halogen',
    period: 4,
    group: 17,
    state: 'liquid',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
    shells: [2, 8, 18, 7],
    summary: 'The only nonmetallic chemical element that is liquid under standard conditions, evaporating into a choking toxic reddish-brown gas.',
    funFact: 'Bromine is named from the Greek word "bromos", meaning "stench" because of its highly offensive, sharp, and irritating smell.',
    discoveredBy: 'Antoine Jérôme Balard, Carl Jacob Löwig',
    year: 1825,
    density: '3.1028 g/cm³',
    meltingPoint: '265.8 K (-7.2 °C)',
    boilingPoint: '332 K (58.8 °C)',
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    mass: 83.798,
    category: 'noble-gas',
    period: 4,
    group: 18,
    state: 'gas',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',
    shells: [2, 8, 18, 8],
    summary: 'A dense, rare noble gas. It glows with a high-intensity bright white/green electric spark under voltage.',
    funFact: 'The length of the meter was officially defined between 1960 and 1983 as exactly 1,650,763.73 wavelengths of light emitted by krypton-86 isotopes!',
    discoveredBy: 'William Ramsay, Morris Travers',
    year: 1898,
    density: '3.749 g/L',
    meltingPoint: '115.79 K (-157.36 °C)',
    boilingPoint: '119.93 K (-153.22 °C)',
  },

  // Period 5
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    mass: 85.468,
    category: 'alkali-metal',
    period: 5,
    group: 1,
    state: 'solid',
    electronConfig: '[Kr] 5s¹',
    shells: [2, 8, 18, 8, 1],
    summary: 'An extremely soft, reactive, silvery alkali metal. It can liquidate on a hot summer day.',
    funFact: 'Rubidium-87 isotopes have been used together with lasers to create the world\'s first Bose-Einstein Condensation phase of matter!',
    discoveredBy: 'Robert Bunsen, Gustav Kirchhoff',
    year: 1861,
    density: '1.532 g/cm³',
    meltingPoint: '312.46 K (39.31 °C)',
    boilingPoint: '961 K (688 °C)',
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    mass: 87.62,
    category: 'alkaline-earth',
    period: 5,
    group: 2,
    state: 'solid',
    electronConfig: '[Kr] 5s²',
    shells: [2, 8, 18, 8, 2],
    summary: 'A highly reactive alkaline earth metal of pale yellow color. Heavily used in flares and fireworks.',
    funFact: 'Strontium compounds generate a brilliant, intense Crimson-carmin red flame. It is the primary element used to color extreme safety flares.',
    discoveredBy: 'Adair Crawford',
    year: 1790,
    density: '2.64 g/cm³',
    meltingPoint: '1050 K (777 °C)',
    boilingPoint: '1655 K (1382 °C)',
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    mass: 107.87,
    category: 'transition-metal',
    period: 5,
    group: 11,
    state: 'solid',
    electronConfig: '[Kr] 4d¹⁰ 5s¹',
    shells: [2, 8, 18, 18, 1],
    summary: 'A highly valuable precious transition metal. It exhibits the highest electrical and thermal conductivity of any metal.',
    funFact: 'Silver ions are highly oligodynamic (biocidal), meaning silver threads can self-sterilize clothing and keep surgical equipment free of germs.',
    discoveredBy: 'Prehistoric humans',
    year: -3000,
    density: '10.49 g/cm³',
    meltingPoint: '1234.93 K (961.78 °C)',
    boilingPoint: '2435 K (2162 °C)',
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    mass: 118.71,
    category: 'post-transition-metal',
    period: 5,
    group: 14,
    state: 'solid',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',
    shells: [2, 8, 18, 18, 4],
    summary: 'A silvery malleable post-transition metal and essential component in bronze and welding alloys.',
    funFact: 'When tin is bent, it emits a bizarre, sharp screaming sound called the "tin cry" as the internal crystals shear and friction with each other!',
    discoveredBy: 'Ancient civilizations',
    year: -3000,
    density: '7.287 g/cm³',
    meltingPoint: '505.08 K (231.93 °C)',
    boilingPoint: '2875 K (2602 °C)',
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    mass: 126.9,
    category: 'halogen',
    period: 5,
    group: 17,
    state: 'solid',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
    shells: [2, 8, 18, 18, 7],
    summary: 'The heaviest stable halogen. Existing as a dark purple-violet metallic crystal that readily sublimates into a breathtaking toxic purple gas.',
    funFact: 'Iodine gets its name from the Greek word "ioeides", meaning violet. It is essential for thyroid metabolic hormone production.',
    discoveredBy: 'Bernard Courtois',
    year: 1811,
    density: '4.933 g/cm³',
    meltingPoint: '386.85 K (113.7 °C)',
    boilingPoint: '457.4 K (184.3 °C)',
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    mass: 131.29,
    category: 'noble-gas',
    period: 5,
    group: 18,
    state: 'gas',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',
    shells: [2, 8, 18, 18, 8],
    summary: 'An extremely rare, dense noble gas. Highly active in extreme camera flashes and ionic spaceship propulsion thrusters.',
    funFact: 'NASA uses Xenon ions as fuel for deep-space missions! Since the ions travel at extreme exhaust speeds, the engines are incredibly fuel-efficient.',
    discoveredBy: 'William Ramsay, Morris Travers',
    year: 1898,
    density: '5.894 g/L',
    meltingPoint: '161.4 K (-111.7 °C)',
    boilingPoint: '165.03 K (-108.09 °C)',
  },

  // Period 6
  {
    number: 55,
    symbol: 'Cs',
    name: 'Caesium',
    mass: 132.91,
    category: 'alkali-metal',
    period: 6,
    group: 1,
    state: 'solid',
    electronConfig: '[Xe] 6s¹',
    shells: [2, 8, 18, 18, 8, 1],
    summary: 'The most reactive, softest metal in the periodic table, cesium explodes instantly when introduced to even trace quantities of water or moisture.',
    funFact: 'Caesium-133 vibration rates define the atomic clock! One second is defined as exactly 9,192,631,770 cycles of cesium radiation.',
    discoveredBy: 'Robert Bunsen, Gustav Kirchhoff',
    year: 1860,
    density: '1.93 g/cm³',
    meltingPoint: '301.59 K (28.44 °C)',
    boilingPoint: '944 K (671 °C)',
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    mass: 137.33,
    category: 'alkaline-earth',
    period: 6,
    group: 2,
    state: 'solid',
    electronConfig: '[Xe] 6s²',
    shells: [2, 8, 18, 18, 8, 2],
    summary: 'A highly reactive alkaline earth metal. Historically used to create highly pure vacuums in television vacuum tubes.',
    funFact: 'Pure barium oxidizes so aggressively that it must be stored under grease or mineral oil to prevent decomposing atmospheric humidity.',
    discoveredBy: 'Carl Wilhelm Scheele',
    year: 1772,
    density: '3.51 g/cm³',
    meltingPoint: '1000 K (727 °C)',
    boilingPoint: '2170 K (1897 °C)',
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    mass: 195.08,
    category: 'transition-metal',
    period: 6,
    group: 10,
    state: 'solid',
    electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    shells: [2, 8, 18, 32, 17, 1],
    summary: 'An extremely dense, malleable, rare, precious metal with incredible heat and chemical resistance.',
    funFact: 'Platinum is highly catalytic: modern vehicles use platinum catalysts in their catalytic converters to convert carbon monoxide into carbon dioxide.',
    discoveredBy: 'Antonio de Ulloa',
    year: 1735,
    density: '21.45 g/cm³',
    meltingPoint: '2041.4 K (1768.3 °C)',
    boilingPoint: '4098 K (3825 °C)',
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    mass: 196.97,
    category: 'transition-metal',
    period: 6,
    group: 11,
    state: 'solid',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    shells: [2, 8, 18, 32, 18, 1],
    summary: 'The ultimate symbol of luxury, an incredibly ductile, non-reactive transition metal that resists all atmospheric erosion.',
    funFact: 'Gold is so incredibly ductile that a single ounce can be drawn into a hair-thin wire stretching over 50 miles long, or flattened into a transparent micron sheet!',
    discoveredBy: 'Prehistoric civilizations',
    year: -4000,
    density: '19.3 g/cm³',
    meltingPoint: '1337.33 K (1064.18 °C)',
    boilingPoint: '3129 K (2856 °C)',
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    mass: 200.59,
    category: 'transition-metal',
    period: 6,
    group: 12,
    state: 'liquid',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    shells: [2, 8, 18, 32, 18, 2],
    summary: 'The only metallic chemical element that is liquid at standard room temperature. Heavy, highly toxic, historically called "quicksilver".',
    funFact: 'Mercury is incredibly dense – solid iron blocks, coins, and billiard balls can float effortlessly like rubber toys in a puddle of liquid mercury!',
    discoveredBy: 'Ancient Egyptians',
    year: -1500,
    density: '13.534 g/cm³',
    meltingPoint: '234.32 K (-38.83 °C)',
    boilingPoint: '629.88 K (356.73 °C)',
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    mass: 207.2,
    category: 'post-transition-metal',
    period: 6,
    group: 14,
    state: 'solid',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    shells: [2, 8, 18, 32, 18, 4],
    summary: 'A heavy, dense post-transition metal with highly toxic compounds, historically prized for its extreme malleability.',
    funFact: 'The Romans used lead extensively for water plumbing (plumbum) and sweeteners for wine. Ancient toxic build-up may have contributed to the empire\'s fall!',
    discoveredBy: 'Middle East civilizations',
    year: -7000,
    density: '11.34 g/cm³',
    meltingPoint: '600.61 K (327.46 °C)',
    boilingPoint: '2022 K (1749 °C)',
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    mass: 222,
    category: 'noble-gas',
    period: 6,
    group: 18,
    state: 'gas',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    shells: [2, 8, 18, 32, 18, 8],
    summary: 'An unstable, highly radioactive noble gas emanating from thorium and uranium decay in granite soil formations.',
    funFact: 'Radon enters homes invisibly through subterranean foundation cracks and represents the second highest cause of lung cancer globally!',
    discoveredBy: 'Ernest Rutherford, Robert Owens',
    year: 1899,
    density: '9.73 g/L',
    meltingPoint: '202 K (-71 °C)',
    boilingPoint: '211.3 K (-61.8 °C)',
  },

  // Period 7 (Actinides / Heavy Radioactive)
  {
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    mass: 238.03,
    category: 'actinide',
    period: 7,
    group: 6, // Placed dynamically for visualization consistency
    state: 'solid',
    electronConfig: '[Rn] 5f³ 6d¹ 7s²',
    shells: [2, 8, 18, 32, 21, 9, 2],
    summary: 'A heavy, metallic silver element. It is naturally fissionable, serving as the main fuel source for nuclear power reactors.',
    funFact: 'Uranium glass (vaseline glass) was popular in the 1920s. It contains small amounts of uranium and glows a brilliant cosmic green under UV light!',
    discoveredBy: 'Martin Heinrich Klaproth',
    year: 1789,
    density: '19.1 g/cm³',
    meltingPoint: '1405.3 K (1132.2 °C)',
    boilingPoint: '4404 K (4131 °C)',
  },
  {
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    mass: 244,
    category: 'actinide',
    period: 7,
    group: 8,
    state: 'synthetic',
    electronConfig: '[Rn] 5f⁶ 7s²',
    shells: [2, 8, 18, 32, 24, 8, 2],
    summary: 'A highly dangerous, synthetic, silver-white radioactive actinide metal. It is highly radioactive and extremely toxic.',
    funFact: 'Just one kilogram of Plutonium can explode with a nuclear thermal energy blast equivalent to 20,000 tons of chemical TNT explosives!',
    discoveredBy: 'Glenn T. Seaborg',
    year: 1940,
    density: '19.816 g/cm³',
    meltingPoint: '912.5 K (639.4 °C)',
    boilingPoint: '3501 K (3228 °C)',
  }
];

export const CATEGORY_COLORS: Record<string, { hex: string; label: string; description: string }> = {
  'alkali-metal': {
    hex: '#FF5722',
    label: 'Alkali Metals',
    description: 'Extremely volatile and reactive metallic elements.'
  },
  'alkaline-earth': {
    hex: '#FFD600',
    label: 'Alkaline Earth',
    description: 'Shiny, moderately reactive solids that burn with bright colorful flames.'
  },
  'transition-metal': {
    hex: '#8D99AE',
    label: 'Transition Metals',
    description: 'High strength, metallic, and lustrous elements that form dense structures.'
  },
  'post-transition-metal': {
    hex: '#00FFB3',
    label: 'Post-Transition Metals',
    description: 'Softer metals lying between transition metals and metalloids.'
  },
  'metalloid': {
    hex: '#00E676',
    label: 'Metalloids',
    description: 'Elements exhibiting properties intermediate between metals and nonmetals.'
  },
  'reactive-nonmetal': {
    hex: '#7C4DFF',
    label: 'Reactive Nonmetals',
    description: 'Abundant, vital non-metallic constituents of life and chemistry.'
  },
  'halogen': {
    hex: '#D500F9',
    label: 'Halogens',
    description: 'Highly electronegative, nonmetallic elements forming intense visual reactive fields.'
  },
  'noble-gas': {
    hex: '#00E5FF',
    label: 'Noble Gases',
    description: 'Highly stable, odorless, inert gases with beautiful glowing atomic discharges.'
  },
  'lanthanide': {
    hex: '#FF80AB',
    label: 'Lanthanides',
    description: 'Rare-earth reactive items with high magnetic and spark emissions.'
  },
  'actinide': {
    hex: '#39FF14',
    label: 'Actinides',
    description: 'Ultra-heavy, naturally unstable, unstable toxic radioactive components.'
  }
};

export const REACTION_CONFIGS: ReactionConfig[] = [
  {
    reactants: ['Na', 'Cl'],
    productName: 'Sodium Chloride (Table Salt)',
    productFormula: 'NaCl',
    description: 'Ionic Bonding: Sodium (alkali metal) donates its valence electron to Chlorine (halogen), establishing a highly stable face-centered cubic ionic salt lattice crystal.',
    visualType: 'ionic'
  },
  {
    reactants: ['H', 'O'],
    productName: 'Water',
    productFormula: 'H₂O',
    description: 'Covalent Bonding: Two Hydrogen atoms share their single valence electrons with one Oxygen atom, forming stable, bent-molecular covalent water particles.',
    visualType: 'covalent'
  },
  {
    reactants: ['Cs', 'H'], // Cesar-Water proxy representation
    productName: 'Violent Caesium Hydroxide Alkaline Jet',
    productFormula: 'CsOH + H₂',
    description: 'Extreme Reaction: Caesium reacts violently with Hydrogen/water vapor to form Caesium hydroxide and release flammable Hydrogen gas in an instant plasma explosion.',
    visualType: 'explosion'
  },
  {
    reactants: ['C', 'O'],
    productName: 'Carbon Dioxide Gas',
    productFormula: 'CO₂',
    description: 'Covalent Carbon Bonds: A single Carbon atom shares two pairs of electrons with two separate Oxygen atoms to assemble linear, atmospheric carbon compounds.',
    visualType: 'covalent'
  },
  {
    reactants: ['Fe', 'O'],
    productName: 'Iron Oxide (Rust)',
    productFormula: 'Fe₂O₃',
    description: 'Metallic Oxidation: Iron loses electrons slowly in contact with environmental Oxygen molecules, transforming the dense transition metal into crumbly red rust.',
    visualType: 'ionic'
  }
];
